lib/powit_web/router.ex
defmodule PowitWeb.Router do
  use PowitWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :powit

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

  scope "/" do
    pipe_through :browser
    pow_routes()
    pow_extension_routes()
  end

  #protected routes
  scope "/", PowitWeb do
    pipe_through [:browser, :protected]
    get "/", PostController, :index

    resources "/posts", PostController do
      resources "/comments", CommentController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PowitWeb do
  #   pipe_through :api
  # end
end

lib/powit/cms/comment.ex
defmodule Powit.CMS.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :message, :string
    field :post_id, :id
    field :user_id, :id

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:message])
    |> validate_required([:message])
  end
end

lib/powit_web/controllers/comment_controller.ex
defmodule PowitWeb.CommentController do
  use PowitWeb, :controller

  alias Powit.CMS
  alias Powit.CMS.Comment

  def index(conn, _params) do
    comments = CMS.list_comments()
    render(conn, "index.html", comments: comments)
  end

  def new(conn, _params) do
    changeset = CMS.change_comment(%Comment{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"comment" => comment_params}) do
    case CMS.create_comment(comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.comment_path(conn, :show, comment))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    comment = CMS.get_comment!(id)
    render(conn, "show.html", comment: comment)
  end

  def edit(conn, %{"id" => id}) do
    comment = CMS.get_comment!(id)
    changeset = CMS.change_comment(comment)
    render(conn, "edit.html", comment: comment, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}) do
    comment = CMS.get_comment!(id)

    case CMS.update_comment(comment, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes.comment_path(conn, :show, comment))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = CMS.get_comment!(id)
    {:ok, _comment} = CMS.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.comment_path(conn, :index))
  end
end

lib/powit_web/views/comment_view.ex
defmodule PowitWeb.CommentView do
  use PowitWeb, :view
end

lib/powit_web/templates/comment/edit.html.eex
<h1>Edit Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :update, @comment)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

lib/powit_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :message %>
  <%= textarea f, :message %>
  <%= error_tag f, :message %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/powit_web/templates/comment/index.html.eex
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.name %></td>
      <td><%= comment.body %></td>
      <td><%= comment.user.email %></td>

      <td>
        <%= link "Show", to: Routes.post_comment_path(@conn, :show, comment) %>
        <%= link "Edit", to: Routes.post_comment_path(@conn, :edit, comment) %>
        <%= link "Delete", to: Routes.post_comment_path(@conn, :delete, comment), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Comment", to: Routes.comment_path(@conn, :new) %></span>

lib/powit_web/templates/comment/new.html.eex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

lib/powit_web/templates/comment/show.html.eex
<h1>Show Comment</h1>

<ul>

  <li>
    <strong>Message:</strong>
    <%= @comment.message %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.comment_path(@conn, :edit, @comment) %></span>
<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>